from __future__ import annotations

from .domain import AssetCategory, AssetDefinition, AssetTier


ASSET_CATALOG: dict[str, AssetDefinition] = {
    "used_car": AssetDefinition(
        asset_key="used_car",
        name="Used Car",
        category=AssetCategory.VEHICLE,
        tier=AssetTier.ENTRY,
        value=150_000,
        price=200_000,
        emoji="🚗",
        flavor_text="Reliable enough to flex from a distance.",
        sort_order=10,
    ),
    "sports_car": AssetDefinition(
        asset_key="sports_car",
        name="Sports Car",
        category=AssetCategory.VEHICLE,
        tier=AssetTier.MID,
        value=1_200_000,
        price=1_800_000,
        emoji="🏎️",
        flavor_text="The engine screams louder than your haters.",
        sort_order=20,
    ),
    "supercar": AssetDefinition(
        asset_key="supercar",
        name="Supercar",
        category=AssetCategory.VEHICLE,
        tier=AssetTier.LUXURY,
        value=5_000_000,
        price=7_500_000,
        emoji="🔥",
        flavor_text="Aerodynamics, absurdity, and attention.",
        sort_order=30,
    ),
    "hypercar": AssetDefinition(
        asset_key="hypercar",
        name="Hypercar",
        category=AssetCategory.VEHICLE,
        tier=AssetTier.ELITE,
        value=25_000_000,
        price=38_000_000,
        emoji="⚡",
        flavor_text="Built for apex predators of the economy.",
        sort_order=40,
    ),
    "fishing_boat": AssetDefinition(
        asset_key="fishing_boat",
        name="Fishing Boat",
        category=AssetCategory.BOAT,
        tier=AssetTier.ENTRY,
        value=400_000,
        price=550_000,
        emoji="🛶",
        flavor_text="Small hull. Big delusions of grandeur.",
        sort_order=50,
    ),
    "speed_boat": AssetDefinition(
        asset_key="speed_boat",
        name="Speed Boat",
        category=AssetCategory.BOAT,
        tier=AssetTier.MID,
        value=2_500_000,
        price=3_700_000,
        emoji="🚤",
        flavor_text="Because roads are too ordinary.",
        sort_order=60,
    ),
    "yacht": AssetDefinition(
        asset_key="yacht",
        name="Yacht",
        category=AssetCategory.BOAT,
        tier=AssetTier.LUXURY,
        value=14_000_000,
        price=21_000_000,
        emoji="🛥️",
        flavor_text="Floating luxury with tax-optimized vibes.",
        sort_order=70,
    ),
    "mega_yacht": AssetDefinition(
        asset_key="mega_yacht",
        name="Mega Yacht",
        category=AssetCategory.BOAT,
        tier=AssetTier.ELITE,
        value=75_000_000,
        price=110_000_000,
        emoji="🛳️",
        flavor_text="A city block of luxury on water.",
        sort_order=80,
    ),
    "small_house": AssetDefinition(
        asset_key="small_house",
        name="Small House",
        category=AssetCategory.PROPERTY,
        tier=AssetTier.ENTRY,
        value=800_000,
        price=1_100_000,
        emoji="🏠",
        flavor_text="Your first step toward real estate dominance.",
        sort_order=90,
    ),
    "modern_house": AssetDefinition(
        asset_key="modern_house",
        name="Modern House",
        category=AssetCategory.PROPERTY,
        tier=AssetTier.MID,
        value=3_000_000,
        price=4_500_000,
        emoji="🏡",
        flavor_text="Glass, steel, and suspiciously expensive chairs.",
        sort_order=100,
    ),
    "luxury_villa": AssetDefinition(
        asset_key="luxury_villa",
        name="Luxury Villa",
        category=AssetCategory.PROPERTY,
        tier=AssetTier.LUXURY,
        value=10_000_000,
        price=15_000_000,
        emoji="🏝️",
        flavor_text="Sunsets included, humility not included.",
        sort_order=110,
    ),
    "mansion": AssetDefinition(
        asset_key="mansion",
        name="Mansion",
        category=AssetCategory.PROPERTY,
        tier=AssetTier.ELITE,
        value=40_000_000,
        price=60_000_000,
        emoji="🏰",
        flavor_text="A personal landmark of financial excess.",
        sort_order=120,
    ),
    "private_island": AssetDefinition(
        asset_key="private_island",
        name="Private Island",
        category=AssetCategory.PROPERTY,
        tier=AssetTier.LEGENDARY,
        value=200_000_000,
        price=300_000_000,
        emoji="🌴",
        flavor_text="When your mailbox needs a boat route.",
        sort_order=130,
    ),
    "storage_unit": AssetDefinition(
        asset_key="storage_unit",
        name="Storage Unit",
        category=AssetCategory.INDUSTRIAL,
        tier=AssetTier.ENTRY,
        value=500_000,
        price=700_000,
        emoji="📦",
        flavor_text="The humble beginning of an empire.",
        sort_order=140,
    ),
    "warehouse": AssetDefinition(
        asset_key="warehouse",
        name="Warehouse",
        category=AssetCategory.INDUSTRIAL,
        tier=AssetTier.MID,
        value=2_200_000,
        price=3_300_000,
        emoji="🏭",
        flavor_text="Scale begins where square footage gets scary.",
        sort_order=150,
    ),
    "distribution_center": AssetDefinition(
        asset_key="distribution_center",
        name="Distribution Center",
        category=AssetCategory.INDUSTRIAL,
        tier=AssetTier.LUXURY,
        value=12_000_000,
        price=18_000_000,
        emoji="🚚",
        flavor_text="Everything moves through your network.",
        sort_order=160,
    ),
    "logistics_hub": AssetDefinition(
        asset_key="logistics_hub",
        name="Logistics Hub",
        category=AssetCategory.INDUSTRIAL,
        tier=AssetTier.ELITE,
        value=60_000_000,
        price=88_000_000,
        emoji="🌐",
        flavor_text="Global flow, local bragging rights.",
        sort_order=170,
    ),
}


def iter_active_assets() -> list[AssetDefinition]:
    return sorted((a for a in ASSET_CATALOG.values() if a.is_active), key=lambda a: (a.sort_order, a.price, a.name))
