from adventure.models.adventure_state import StageTag, StageTemplate

DUNGEON_EVENTS = [
    StageTemplate(
        key="dungeon_entrance",
        title="Hidden Dungeon Entrance",
        beats=[
            "The ground collapses beneath old roots.",
            "A staircase descends into a sealed dungeon chamber.",
        ],
        choices=["Descend together", "Scout first", "Seal it and leave"],
        tag=StageTag.BOSS,
        party_only=True,
        min_adv_level=16,
    ),
    StageTemplate(
        key="flooded_cave",
        title="Flooded Cave",
        beats=[
            "A cave entrance exhales cold air and dripping echoes.",
            "Fresh claw marks run along the stone walls.",
        ],
        choices=["Light torches and enter", "Set bait outside", "Mark it on map"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_1",
        title="Sunken Corridor 1",
        beats=[
            "The party spots sunken corridor marker 1 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=6,
    ),
    StageTemplate(
        key="dungeon_depth_2",
        title="Sunken Corridor 2",
        beats=[
            "The party spots sunken corridor marker 2 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=6,
    ),
    StageTemplate(
        key="dungeon_depth_3",
        title="Sunken Corridor 3",
        beats=[
            "The party spots sunken corridor marker 3 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=6,
    ),
    StageTemplate(
        key="dungeon_depth_4",
        title="Sunken Corridor 4",
        beats=[
            "The party spots sunken corridor marker 4 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=6,
    ),
    StageTemplate(
        key="dungeon_depth_5",
        title="Sunken Corridor 5",
        beats=[
            "The party spots sunken corridor marker 5 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=6,
    ),
    StageTemplate(
        key="dungeon_depth_6",
        title="Sunken Corridor 6",
        beats=[
            "The party spots sunken corridor marker 6 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_7",
        title="Sunken Corridor 7",
        beats=[
            "The party spots sunken corridor marker 7 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_8",
        title="Sunken Corridor 8",
        beats=[
            "The party spots sunken corridor marker 8 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_9",
        title="Sunken Corridor 9",
        beats=[
            "The party spots sunken corridor marker 9 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_10",
        title="Sunken Corridor 10",
        beats=[
            "The party spots sunken corridor marker 10 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_11",
        title="Sunken Corridor 11",
        beats=[
            "The party spots sunken corridor marker 11 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=7,
    ),
    StageTemplate(
        key="dungeon_depth_12",
        title="Sunken Corridor 12",
        beats=[
            "The party spots sunken corridor marker 12 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_13",
        title="Sunken Corridor 13",
        beats=[
            "The party spots sunken corridor marker 13 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_14",
        title="Sunken Corridor 14",
        beats=[
            "The party spots sunken corridor marker 14 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_15",
        title="Sunken Corridor 15",
        beats=[
            "The party spots sunken corridor marker 15 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_16",
        title="Sunken Corridor 16",
        beats=[
            "The party spots sunken corridor marker 16 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_17",
        title="Sunken Corridor 17",
        beats=[
            "The party spots sunken corridor marker 17 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=8,
    ),
    StageTemplate(
        key="dungeon_depth_18",
        title="Sunken Corridor 18",
        beats=[
            "The party spots sunken corridor marker 18 carved into old stone.",
            "A strange hush falls over the trail before everything gets louder.",
        ],
        choices=["Disarm the floor plates", "Send one scout", "Retreat to camp"],
        tag=StageTag.TRAP,
        min_adv_level=9,
    ),
]
